apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  server:
                    access-log: false
                    base-path: "/"
                  connections:
                    kafka-cluster:
                      properties:
                        bootstrap.servers: "kafka-service:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akhq-service
spec:
  selector:
    app: akhq
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
